create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  razorpay_order_id text not null unique,
  razorpay_payment_id text not null unique,
  status text not null default 'PAID' check (status in ('PAID', 'FULFILLED', 'CANCELLED')),
  amount integer not null,
  currency text not null default 'INR',
  customer jsonb not null,
  items jsonb not null,
  subtotal numeric(12, 2) not null,
  tax numeric(12, 2) not null default 0,
  shipping_fee numeric(12, 2) not null default 0,
  total numeric(12, 2) not null,
  paid_at timestamptz not null default now(),
  notification_sent_at timestamptz,
  notification_id text,
  notification_attempted_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

create or replace function public.claim_order_notification(p_order_id bigint)
returns setof public.orders
language sql
security definer
set search_path = public
as $$
  update public.orders
  set notification_attempted_at = now()
  where id = p_order_id
    and notification_sent_at is null
    and (notification_attempted_at is null or notification_attempted_at < now() - interval '5 minutes')
  returning *;
$$;

revoke all on function public.claim_order_notification(bigint) from public, anon, authenticated;
grant execute on function public.claim_order_notification(bigint) to service_role;